-- Ghost-Prime schema (Phase 1). Idempotent: safe to run on every startup.

CREATE TABLE IF NOT EXISTS sessions (
  id         TEXT    PRIMARY KEY,
  started_at INTEGER NOT NULL,
  ended_at   INTEGER,
  summary    TEXT            -- auto-generated by the agent on session end (Phase 4)
);

CREATE TABLE IF NOT EXISTS memories (
  id            TEXT    PRIMARY KEY,
  session_id    TEXT    REFERENCES sessions(id),
  type          TEXT    NOT NULL,   -- 'fact' | 'preference' | 'task' | 'event'
  content       TEXT    NOT NULL,
  embedding     BLOB,               -- Float32Array as BLOB (unused until Phase 4)
  importance    INTEGER DEFAULT 5,
  created_at    INTEGER NOT NULL,
  last_accessed INTEGER
);

CREATE TABLE IF NOT EXISTS preferences (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memories_session ON memories(session_id);
